config/routes.rb
Rails.application.routes.draw do
  resources :decks
  resources :cards, only: [:index]
  devise_for :users
  
  root to: "decks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/deck.rb
class Deck < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
      
    protected
      
    def configure_permitted_parameters
      added_attrs = %i[username email password password_confirmation remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
 
  def index
    query = params[:query]
    if query.present?
      @cards = Card.where("name LIKE ?", "%#{query}%")
    else
    @cards = Card.all
    end
  end
      
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deck, only: %i[ show edit update destroy ]

  # GET /decks or /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1 or /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks or /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to deck_url(@deck), notice: "Deck was successfully created." }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1 or /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to deck_url(@deck), notice: "Deck was successfully updated." }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1 or /decks/1.json
  def destroy
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url, notice: "Deck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deck_params
      params.require(:deck).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/index.html.erb
<h1>Card Search Results</h1>

<% if @cards.any? %>
  <div class="card-images">
    <% @cards.each do |card| %>
      <div class="card-image">
        <img src="<%= card.image %>" alt="<%= card.name %>" />
      </div>
    <% end %>
  </div>
<% else %>
  <p>No cards found.</p>
<% end %>

app/views/decks/_deck.html.erb
<div id="<%= dom_id deck %>">
  <p>
    <strong>Title:</strong>
    <%= deck.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= deck.description %>
  </p>

</div>

app/views/decks/_form.html.erb
<%= form_with(model: deck) do |form| %>
  <% if deck.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
        <% deck.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render "form", deck: @deck %>

<br>

<div>
  <%= link_to "Show this deck", @deck %> |
  <%= link_to "Back to decks", decks_path %>
</div>

app/views/decks/index.html.erb
<h1>Decks</h1>

<div id="decks">
  <% @decks.each do |deck| %>
    <%= render deck %>
    <p>
      <%= link_to "Show this deck", deck %>
    </p>
  <% end %>
</div>

<%= link_to "New deck", new_deck_path %>

<%= form_tag(cards_path, method: :get) do %>
  <%= text_field_tag :query, params[:query], placeholder: "Search cards..." %>
  <%= submit_tag "Search" %>
<% end %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render "form", deck: @deck %>

<br>

<div>
  <%= link_to "Back to decks", decks_path %>
</div>

app/views/decks/show.html.erb
<%= render @deck %>

<div>
  <%= link_to "Edit this deck", edit_deck_path(@deck) %> |
  <%= link_to "Back to decks", decks_path %>

  <%= button_to "Destroy this deck", @deck, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MtgDeckbuilder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <% if user_signed_in? %>
    <%= link_to "New Deck", new_deck_path %>
    <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
    
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>